name: Discord Notifications

on:
  push:
  pull_request:
  issues:
  release:
  create:
  delete:
  fork:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🔔 **${{ github.event_name }}**
            
            📦 Repo: ${{ github.repository }}
            👤 Auteur: ${{ github.actor }}
            
            🔗 https://github.com/${{ github.repository }}
